# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# Ordered by weight, lowest first.

[[main]]
name = "文章"
pageRef = "posts"
weight = 1

[[main]]
name = "作品"
pageRef = "portfolio"
weight = 2

[[main]]
name = "关于"
pageRef = "about"
weight = 3

[[main]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://x.com/xianpengshen"
  weight = 200

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/shenxianpeng"
  weight = 400

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice.

[[footer]]
  name = "随笔"
  pageRef = "misc"
  weight = 10

[[footer]]
  name = "归档"
  pageRef = "archive"
  weight = 20

[[footer]]
  name = "标签"
  pageRef = "tags"
  weight = 30

[[footer]]
  name = "RSS"
  url = "/zh-cn/index.xml"
  weight = 40
