#!/usr/bin/env python3
"""Generate the CSS for the home page's animated product demos.

The cpp-linter, AccessLens and keelinfra demos
(layouts/partials/home/demo-{cpp-linter,accesslens,keelinfra}.html) are pure CSS. Each element that appears, swaps or
moves has its own keyframes, and a scene change touches dozens of them, so the
timelines live here as plain data -- "visible from 26% to 49% of the loop",
"cursor at (474, 238) at 42%" -- and this script writes the CSS.

The output replaces the block between the BEGIN/END markers in
assets/css/custom.css. Edit this script, not that block. The Keelhaven demo is
not generated: it is ported by hand from keelhaven.app and lives outside the
markers.

    python3 .github/scripts/gen_demo_css.py           # rewrite the block
    python3 .github/scripts/gen_demo_css.py --check   # exit 1 if it is stale

Timings are percentages of each loop (cpp-linter 20s, AccessLens 16s,
keelinfra 18s). The
header comment of each partial says what happens when. Cursor coordinates are
pixels inside the fixed-size demo window, measured to the pointer's tip.
"""

import argparse
import os
import sys

REPO_ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
CSS_PATH = os.path.join(REPO_ROOT, "assets", "css", "custom.css")
BEGIN = "/* BEGIN generated by .github/scripts/gen_demo_css.py -- edit the script, not this block */\n"
END = "/* END generated by .github/scripts/gen_demo_css.py */\n"

# Default fade, in percent of the loop, when an element appears or disappears.
F = 0.8


def vis(name, intervals, f=F):
    """Opacity keyframes: visible during each (start, end) window, else hidden.

    Windows are percentages, in order and non-overlapping. A window starting at
    0 or ending at 100 is visible across the loop boundary.
    """
    pts = {}
    if intervals[0][0] > 0:
        pts[0] = 0
    for a, b in intervals:
        if a > 0:
            pts[round(a - f, 2)] = 0
            pts[a] = 1
        else:
            pts[0] = 1
        pts[b] = 1
        if b < 100:
            pts[round(b + f, 2)] = 0
        else:
            pts[100] = 1
    if intervals[-1][1] < 100:
        pts[100] = 0
    body = " ".join(f"{k:g}% {{ opacity: {pts[k]}; }}" for k in sorted(pts))
    return f"@keyframes {name} {{ {body} }}"


def props(name, frames):
    """Keyframes from (selector, declarations) pairs, written as given."""
    body = " ".join(f"{k} {{ {v} }}" for k, v in frames)
    return f"@keyframes {name} {{ {body} }}"


# ---- cpp-linter (20s loop) ---------------------------------------------------
# Scenes: 0-25 thread-comments (Conversation), 25-50 format-review (Files
# changed), 50-75 step-summary (Checks), 75-100 auto-fix (Conversation again,
# with the pushed commit). Scene layers fade in and out 2% inside each window
# so the loop boundary is never visible mid-scene.

cl = """/* cpp-linter: four scenes in a GitHub pull request, one per action input. */

.home-demo-cl { display: flex; flex-direction: column; align-items: center; width: 100%; margin-top: 4.5rem; }
.cl-demo { display: flex; flex-direction: column; align-items: center; gap: 1.25rem; }
.cl-demo-chips { display: flex; flex-wrap: wrap; justify-content: center; gap: 0.5rem; }
.cl-demo-chip { padding: 0.3rem 0.75rem; border: 1px solid rgb(var(--color-neutral-600)); border-radius: 9999px; background: transparent; color: rgb(var(--color-neutral-400)); font-family: var(--font-code); font-size: 0.8125rem; }
.cl-demo-v1 { animation: cl-demo-v1 20s ease infinite; }
.cl-demo-v2 { animation: cl-demo-v2 20s ease infinite; }
.cl-demo-v3 { animation: cl-demo-v3 20s ease infinite; }
.cl-demo-v4 { animation: cl-demo-v4 20s ease infinite; }

.cl-demo-window { width: 720px; height: 540px; overflow: hidden; border: 1px solid #d0d7de; border-radius: 14px; background: #fff; color: #1f2328; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Noto Sans", Helvetica, Arial, sans-serif; font-size: 13px; line-height: 1.4; text-align: left; box-shadow: 0 40px 100px rgb(0 0 0 / 0.55), 0 0 0 1px rgb(255 255 255 / 0.08); }
.cl-demo-pr { padding: 14px 16px 6px; font-size: 18px; }
.cl-demo-open { display: inline-block; margin-left: 6px; padding: 1px 10px; border-radius: 999px; background: #1f883d; color: #fff; font-size: 12px; font-weight: 500; vertical-align: 3px; }
.cl-demo-tabs { display: flex; gap: 4px; padding: 0 16px; border-bottom: 1px solid #d0d7de; color: #59636e; }
.cl-demo-tab { position: relative; padding: 10px 8px; }
.cl-demo-tab em { margin-left: 4px; padding: 0 6px; border-radius: 999px; background: #eff2f5; font-size: 11px; font-style: normal; }
.cl-demo-u { position: absolute; left: 0; right: 0; bottom: -1px; height: 2px; background: #fd8c73; opacity: 0; }
.cl-demo-u-conv { animation: cl-demo-u-conv 20s linear infinite; }
.cl-demo-u-files { animation: cl-demo-u-files 20s linear infinite; }
.cl-demo-u-checks { animation: cl-demo-u-checks 20s linear infinite; }

.cl-demo-stage { position: relative; height: 440px; }
.cl-demo-scene { position: absolute; inset: 0; padding: 14px 16px; opacity: 0; }
.cl-demo-s-conv { opacity: 1; animation: cl-demo-s-conv 20s ease infinite; }
.cl-demo-s-files { animation: cl-demo-s-files 20s ease infinite; }
.cl-demo-s-checks { animation: cl-demo-s-checks 20s ease infinite; }
.cl-demo-muted { color: #59636e; }
.cl-demo-link { color: #0969da; }

.cl-demo-event { display: flex; align-items: center; gap: 10px; padding: 4px 0 10px 8px; color: #59636e; }
.cl-demo-event code { margin-left: auto; font-family: var(--font-code); font-size: 12px; background: none; }
.cl-demo-dot { width: 10px; height: 10px; border: 2px solid #d0d7de; border-radius: 50%; background: #fff; }
.cl-demo-dot-you { border-color: #8250df; }
.cl-demo-comment, .cl-demo-review, .cl-demo-summary { border: 1px solid #d0d7de; border-radius: 8px; overflow: hidden; }
.cl-demo-in-comment { animation: cl-demo-in-comment 20s ease infinite; }
.cl-demo-in-review { animation: cl-demo-in-review 20s ease infinite; }
.cl-demo-in-summary { animation: cl-demo-in-summary 20s ease infinite; }
.cl-demo-chead { display: flex; align-items: center; gap: 6px; padding: 8px 12px; border-bottom: 1px solid #d0d7de; background: #f6f8fa; }
.cl-demo-avatar { display: inline-flex; align-items: center; justify-content: center; width: 20px; height: 20px; border-radius: 50%; background: #1f2328; }
.cl-demo-bot { padding: 0 6px; border: 1px solid #d0d7de; border-radius: 999px; color: #59636e; font-size: 11px; line-height: 16px; }
.cl-demo-report { padding: 10px 14px 12px; }
.cl-demo-report p { margin: 6px 0; }
.cl-demo-h { display: flex; align-items: center; gap: 8px; padding-bottom: 6px; border-bottom: 1px solid #d8dee4; font-size: 20px; font-weight: 600; }
.cl-demo-indent { padding-left: 18px; font-family: var(--font-code); font-size: 12px; }
.cl-demo-small { font-size: 11.5px; }

.cl-demo-slot { position: relative; margin-top: 12px; height: 176px; }
.cl-demo-status, .cl-demo-push { position: absolute; inset: 0 0 auto; }
.cl-demo-status { display: flex; align-items: center; gap: 12px; padding: 14px 16px; border: 1px solid #d0d7de; border-radius: 8px; opacity: 0; animation: cl-demo-in-fail 20s ease infinite; }
.cl-demo-status div { display: flex; flex-direction: column; }
.cl-demo-status span { color: #59636e; font-size: 12px; }
.cl-demo-push { opacity: 0; animation: cl-demo-in-push 20s ease infinite; }
.cl-demo-push .cl-demo-event { color: #1f2328; }
.cl-demo-pushbox { overflow: hidden; border: 1px solid #d0d7de; border-radius: 8px; }
.cl-demo-pushhead { display: flex; justify-content: space-between; padding: 8px 12px; border-bottom: 1px solid #d0d7de; background: #f6f8fa; font-weight: 600; }
.cl-demo-pushhead code { font-family: var(--font-code); font-size: 12px; font-weight: 400; color: #59636e; background: none; }
.cl-demo-pushbox .cl-demo-line { grid-template-columns: 40px minmax(0, 1fr); }

.cl-demo-file { overflow: hidden; border: 1px solid #d0d7de; border-radius: 8px; }
.cl-demo-filehead { padding: 8px 12px; border-bottom: 1px solid #d0d7de; background: #f6f8fa; font-family: var(--font-code); font-size: 12px; }
.cl-demo-line { display: grid; grid-template-columns: 40px 40px minmax(0, 1fr); font-family: var(--font-code); font-size: 12px; line-height: 21px; }
.cl-demo-line b { padding-right: 10px; color: #59636e; font-weight: 400; text-align: right; }
.cl-demo-line code { padding-left: 10px; white-space: pre; font-family: inherit; font-size: inherit; background: none; }
.cl-demo-hunk { background: #ddf4ff; color: #59636e; }
.cl-demo-hunk b { background: #b6e3ff; }
.cl-demo-add { background: #e6ffec; }
.cl-demo-add b { background: #ccffd8; }
.cl-demo-del { background: #ffebe9; }
.cl-demo-del b { background: #ffd7d5; }
.cl-demo-line .k { color: #cf222e; }
.cl-demo-line .t { color: #8250df; }
.cl-demo-line .s { color: #0a3069; }
.cl-demo-review { margin: 10px 12px 12px; }
.cl-demo-suggest { margin: 10px 12px 12px; overflow: hidden; border: 1px solid #d0d7de; border-radius: 6px; }
.cl-demo-suggest-head { padding: 5px 10px; border-bottom: 1px solid #d0d7de; background: #f6f8fa; color: #59636e; font-size: 12px; }
.cl-demo-suggest .cl-demo-line { grid-template-columns: 40px minmax(0, 1fr); }
.cl-demo-actions { display: flex; justify-content: flex-end; gap: 8px; padding: 8px 10px; border-top: 1px solid #d0d7de; background: #f6f8fa; }
.cl-demo-btn { padding: 4px 12px; border: 1px solid #d0d7de; border-radius: 6px; background: #fff; font-size: 12px; font-weight: 500; white-space: nowrap; }
.cl-demo-btn-off { background: #f6f8fa; color: #818b98; }

.cl-demo-run { display: grid; grid-template-columns: 150px minmax(0, 1fr); gap: 16px; height: 100%; }
.cl-demo-side { display: flex; flex-direction: column; gap: 8px; padding-right: 12px; border-right: 1px solid #d0d7de; }
.cl-demo-side-on { padding: 5px 8px; border-radius: 6px; background: #eff2f5; font-weight: 600; }
.cl-demo-side-label { margin-top: 8px; font-size: 12px; }
.cl-demo-job { display: flex; align-items: center; gap: 8px; padding: 0 8px; }
.cl-demo-main { display: flex; flex-direction: column; gap: 12px; }
.cl-demo-trigger { display: flex; justify-content: space-between; padding: 12px 14px; border: 1px solid #d0d7de; border-radius: 8px; }
.cl-demo-summary-head { padding: 8px 12px; border-bottom: 1px solid #d0d7de; background: #f6f8fa; font-weight: 600; }
"""
# Keyframes: scene layers, tab underlines, then content appearing in a scene.
cl_k = [
 vis("cl-demo-s-conv", [(2, 24), (76, 98)]),
 vis("cl-demo-s-files", [(26, 49)]),
 vis("cl-demo-s-checks", [(51, 74)]),
 vis("cl-demo-u-conv", [(0, 25), (75, 100)], 0.01),
 vis("cl-demo-u-files", [(25, 50)], 0.01),
 vis("cl-demo-u-checks", [(50, 75)], 0.01),
 vis("cl-demo-in-comment", [(5, 100)]),
 vis("cl-demo-in-fail", [(10, 24)]),
 vis("cl-demo-in-push", [(80, 100)]),
 vis("cl-demo-in-review", [(30, 100)]),
 vis("cl-demo-in-summary", [(55, 100)]),
]
# The chip row: the input behind the current scene is highlighted.
on = "background: rgb(var(--color-primary-400)); border-color: rgb(var(--color-primary-400)); color: rgb(var(--color-neutral-900));"
off = "background: transparent; border-color: rgb(var(--color-neutral-600)); color: rgb(var(--color-neutral-400));"
for i, (a, b) in enumerate([(0, 25), (25, 50), (50, 75), (75, 100)], 1):
    fr = []
    if a > 0: fr += [("0%", off), (f"{a-0.5:g}%", off)]
    fr += [(f"{a}%" if a else "0%", on), (f"{b-0.5:g}%" if b < 100 else "100%", on)]
    if b < 100: fr += [(f"{b}%", off), ("100%", off)]
    cl_k.append(props(f"cl-demo-v{i}", fr))

# ---- AccessLens for Jira (16s loop) ------------------------------------------
# 0-33 Explore: summary and rows appear (3-9). 30-33 the cursor clicks the
# Reviews tab. 34-97 Reviews: Confirm PAY at 43, Confirm WEB at 50, Remediate
# HR at 58, Sign off at 68; the banner appears at 70.

al = """/* keelapps: AccessLens for Jira, reverse lookup then an access review. */

.home-demo-al { border-radius: 20px; background: rgb(var(--color-primary-200)); padding: 28px; display: flex; justify-content: center; overflow: hidden; }
.al-demo-win { position: relative; width: 600px; height: 452px; overflow: hidden; border: 1px solid #dfe1e6; border-radius: 10px; background: #fff; color: #172b4d; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Noto Sans", sans-serif; font-size: 12.5px; line-height: 1.4; text-align: left; box-shadow: 0 24px 60px rgb(9 30 66 / 0.25), 0 2px 6px rgb(9 30 66 / 0.12); }
.al-demo-head { display: flex; align-items: baseline; gap: 10px; height: 44px; box-sizing: border-box; padding: 12px 16px 0; }
.al-demo-head strong { font-size: 17px; }
.al-demo-head span, .al-demo-muted { color: #42526e; }
.al-demo-head span { font-size: 12px; }
.al-demo-tabs { position: relative; display: flex; height: 36px; box-sizing: border-box; padding: 0 16px; border-bottom: 2px solid #ebecf0; }
.al-demo-tabs span { width: 84px; padding-top: 9px; text-align: center; color: #42526e; font-weight: 500; }
.al-demo-bar { position: absolute; left: 16px; bottom: -2px; width: 84px; height: 2px; background: #0052cc; animation: al-demo-bar 16s ease infinite; }
.al-demo-body { position: relative; height: 372px; }
.al-demo-explore, .al-demo-review { position: absolute; inset: 0; padding: 14px 16px; opacity: 0; }
.al-demo-explore { animation: al-demo-explore 16s ease infinite; }
.al-demo-review { animation: al-demo-review 16s ease infinite; }
.al-demo-row { display: flex; gap: 10px; }
.al-demo-field { display: flex; flex-direction: column; gap: 3px; font-size: 11px; font-weight: 600; color: #42526e; }
.al-demo-field b { min-width: 118px; padding: 5px 8px; border: 2px solid #dfe1e6; border-radius: 3px; background: #fafbfc; color: #172b4d; font-size: 12.5px; font-weight: 400; }
.al-demo-field-wide b { min-width: 150px; }
.al-demo-ph { color: #7a869a !important; }
.al-demo-prov { margin: 10px 0 8px; font-size: 12px; }
.al-demo-sum { display: flex; align-items: center; justify-content: space-between; gap: 8px; height: 28px; margin-bottom: 8px; opacity: 0; animation: al-demo-sum 16s ease infinite; }
.al-demo-btn { padding: 3px 9px; border-radius: 3px; background: #ebecf0; color: #172b4d; font-size: 12px; font-weight: 500; white-space: nowrap; }
.al-demo-btn-danger { background: #ffebe6; color: #bf2600; }
.al-demo-table { border: 1px solid #ebecf0; border-radius: 3px; }
.al-demo-th, .al-demo-tr { display: grid; align-items: center; padding: 0 10px; border-bottom: 1px solid #ebecf0; }
.al-demo-t1 .al-demo-th, .al-demo-t1 .al-demo-tr { grid-template-columns: 150px 170px 110px minmax(0, 1fr); }
.al-demo-t2 .al-demo-th, .al-demo-t2 .al-demo-tr { grid-template-columns: 118px 214px 88px minmax(0, 1fr); font-size: 11.5px; }
.al-demo-t2 .al-demo-btn { padding: 3px 7px; font-size: 11.5px; }
.al-demo-th { height: 26px; background: #f4f5f7; color: #42526e; font-size: 11px; font-weight: 600; }
.al-demo-tr { height: 36px; white-space: nowrap; }
.al-demo-t2 .al-demo-tr { height: 40px; }
.al-demo-tr:last-child { border-bottom: 0; }
.al-demo-r1, .al-demo-r2, .al-demo-r3 { opacity: 0; }
.al-demo-r1 { animation: al-demo-r1 16s ease infinite; }
.al-demo-r2 { animation: al-demo-r2 16s ease infinite; }
.al-demo-r3 { animation: al-demo-r3 16s ease infinite; }
.al-b { display: inline-block; margin-right: 4px; padding: 1px 6px; border-radius: 3px; font-size: 10.5px; font-style: normal; font-weight: 700; letter-spacing: 0.04em; text-transform: uppercase; }
.al-b-browse, .al-b-pending { background: #ebecf0; color: #42526e; }
.al-b-edit, .al-b-open { background: #deebff; color: #0052cc; }
.al-b-manage { background: #eae6ff; color: #403294; }
.al-b-high, .al-b-remediate { background: #ffebe6; color: #bf2600; }
.al-b-confirmed { background: #e3fcef; color: #006644; }

.al-demo-rhead { display: flex; align-items: center; justify-content: space-between; height: 30px; }
.al-demo-rhead strong { font-size: 14px; }
.al-demo-signoff { position: relative; width: 150px; height: 28px; border-radius: 3px; background: #ebecf0; animation: al-demo-signoff 16s ease infinite; }
.al-demo-signoff b { position: absolute; inset: 0; display: flex; align-items: center; justify-content: center; font-size: 12px; font-weight: 500; }
.al-demo-stats { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); height: 50px; margin: 10px 0 8px; }
.al-demo-stats > div { display: flex; flex-direction: column; }
.al-demo-stats .al-demo-muted { font-size: 11px; }
.al-demo-num { position: relative; height: 26px; font-size: 20px; font-weight: 600; }
.al-demo-sw { position: absolute; inset: 0 auto auto 0; opacity: 0; }
.al-demo-dec { position: relative; height: 18px; }
.al-demo-acts { display: flex; gap: 6px; }
.al-demo-banner { margin-top: 10px; padding: 8px 12px; border-radius: 3px; background: #e3fcef; color: #006644; font-size: 12px; opacity: 0; animation: al-demo-banner 16s ease infinite; }
.al-demo-banner code { padding: 0 3px; background: rgb(0 0 0 / 0.06); font-size: 11px; }
.al-demo-cursor { position: absolute; left: 0; top: 0; z-index: 3; opacity: 0; filter: drop-shadow(0 1px 2px rgb(0 0 0 / 0.35)); pointer-events: none; animation: al-demo-cursor 16s ease infinite; }
"""
# Values that swap in place (decision badges, counters, the sign-off label):
# each is visible only during its windows.
sw = {
 "d1a": [(0, 44)], "d1b": [(44, 100)], "d2a": [(0, 51)], "d2b": [(51, 100)],
 "d3a": [(0, 59)], "d3b": [(59, 100)],
 "c0": [(0, 44)], "c1": [(44, 51)], "c2": [(51, 100)],
 "x0": [(0, 59)], "x1": [(59, 100)],
 "p3": [(0, 44)], "p2": [(44, 51)], "p1": [(51, 59)], "p0": [(59, 69)], "q0": [(59, 100)],
 "done": [(69, 100)],
}
for k in sw:
    al += f".al-demo-{k} {{ animation: al-demo-{k} 16s linear infinite; }}\n"
al += ".al-demo-k1 { animation: al-demo-k1 16s ease infinite; }\n.al-demo-k2 { animation: al-demo-k2 16s ease infinite; }\n.al-demo-k3 { animation: al-demo-k3 16s ease infinite; }\n"
al += ".al-demo-go { color: #fff; }\n"
al_k = [
 vis("al-demo-explore", [(1, 33)]),
 vis("al-demo-review", [(34, 97)]),
 vis("al-demo-sum", [(3, 100)]),
 vis("al-demo-r1", [(5, 100)]),
 vis("al-demo-r2", [(7, 100)]),
 vis("al-demo-r3", [(9, 100)]),
 vis("al-demo-banner", [(70, 100)]),
]
for k, iv in sw.items():
    al_k.append(vis(f"al-demo-{k}", iv, 0.3))
al_k.append(props("al-demo-bar", [("0%, 33%", "transform: none;"), ("35%, 96%", "transform: translateX(168px);"), ("98%, 100%", "transform: none;")]))
al_k.append(props("al-demo-signoff", [("0%, 58.5%", "background: #ebecf0; color: #a5adba;"), ("59%, 67.5%", "background: #0052cc; color: #fff;"), ("68%, 68.8%", "background: #0747a6; color: #fff; transform: scale(0.97);"), ("69%, 100%", "background: #ebecf0; color: #42526e; transform: none;")]))
for i, t in [(1, 43), (2, 50), (3, 58)]:
    base = "#ffebe6" if i == 3 else "#ebecf0"
    press = "#ffbdad" if i == 3 else "#c1c7d0"
    al_k.append(props(f"al-demo-k{i}", [(f"0%, {t-0.1:g}%", f"background: {base}; transform: none;"), (f"{t}%, {t+0.8:g}%", f"background: {press}; transform: scale(0.95);"), (f"{t+1.2:g}%, 100%", f"background: {base}; transform: none;")]))
def c(x, y, s=1):
    """Cursor transform with the pointer's tip at (x, y), optionally pressed."""
    return f"transform: translate({x-1}px, {y-1}px)" + (f" scale({s})" if s != 1 else "") + ";"
cur = [("0%, 18%", "opacity: 0; " + c(430, 400)), ("20%", "opacity: 1; " + c(420, 380)),
 ("30%", "opacity: 1; " + c(226, 62)), ("31%", "opacity: 1; " + c(226, 62, 0.88)), ("32.5%", "opacity: 1; " + c(226, 62)),
 ("42%", "opacity: 1; " + c(474, 238)), ("43%", "opacity: 1; " + c(474, 238, 0.88)), ("44%", "opacity: 1; " + c(474, 238)),
 ("49%", "opacity: 1; " + c(474, 278)), ("50%", "opacity: 1; " + c(474, 278, 0.88)), ("51%", "opacity: 1; " + c(474, 278)),
 ("57%", "opacity: 1; " + c(538, 318)), ("58%", "opacity: 1; " + c(538, 318, 0.88)), ("59%", "opacity: 1; " + c(538, 318)),
 ("67%", "opacity: 1; " + c(509, 109)), ("68%", "opacity: 1; " + c(509, 109, 0.88)), ("69%", "opacity: 1; " + c(509, 109)),
 ("72%", "opacity: 1; " + c(540, 170)), ("74%, 100%", "opacity: 0; " + c(545, 180))]
al_k.append(props("al-demo-cursor", cur))


# ---- keelinfra (18s loop) -----------------------------------------------------
# 0-45 terminal: ./configure typed (2-7) and confirmed (9), ./install typed
# (11-13), the ten plays of playbooks/install.yml (15-33), the recap (36-39).
# 47-97 upgrade matrix: each path's four checks turn green column by column,
# rows staggered; the session assertion's echo appears at 90.

ki = """/* keelinfra: ./configure and ./install, then the nightly upgrade matrix. */

.home-demo-ki { display: flex; justify-content: center; }
.ki-demo-win { width: 600px; height: 430px; overflow: hidden; border: 1px solid #30363d; border-radius: 10px; background: #0d1117; color: #e6edf3; text-align: left; box-shadow: 0 24px 60px rgb(0 0 0 / 0.5); }
.ki-demo-bar { position: relative; display: flex; align-items: center; height: 32px; padding: 0 12px; border-bottom: 1px solid #30363d; background: #161b22; }
.ki-demo-dots { display: flex; gap: 6px; }
.ki-demo-dots i { width: 10px; height: 10px; border-radius: 50%; background: #30363d; }
.ki-demo-title { position: absolute; inset: 0; text-align: center; color: #8b949e; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; font-size: 12px; }
.ki-demo-title b { position: absolute; inset: 0; display: flex; align-items: center; justify-content: center; font-weight: 500; opacity: 0; }
.ki-demo-t1 { opacity: 1; animation: ki-demo-t1 18s linear infinite; }
.ki-demo-t2 { animation: ki-demo-t2 18s linear infinite; }
.ki-demo-body { position: relative; height: 398px; }
.ki-demo-term, .ki-demo-matrix { position: absolute; inset: 0; padding: 14px 16px; opacity: 0; }
.ki-demo-term { font-family: var(--font-code); font-size: 12px; line-height: 17px; animation: ki-demo-term 18s ease infinite; }
.ki-demo-matrix { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Noto Sans", sans-serif; font-size: 12.5px; animation: ki-demo-matrix 18s ease infinite; }
.ki-demo-ln { overflow: hidden; white-space: nowrap; }
.ki-demo-ps { color: #7ee787; }
.ki-demo-type { display: inline-block; overflow: hidden; vertical-align: bottom; white-space: nowrap; }
.ki-demo-type1 { width: 36ch; animation: ki-demo-type1 18s infinite; }
.ki-demo-type2 { width: 9ch; animation: ki-demo-type2 18s infinite; }
.ki-demo-ok { color: #7ee787; }
.ki-demo-play { color: #8b949e; }
.ki-demo-host { display: inline-block; width: 12ch; color: #e3b341; }
.ki-demo-mhead { display: flex; align-items: baseline; justify-content: space-between; padding-bottom: 12px; }
.ki-demo-mhead strong { font-size: 15px; }
.ki-demo-mhead span, .ki-demo-row em { color: #8b949e; font-style: normal; }
.ki-demo-grid { display: grid; grid-template-columns: 170px repeat(4, minmax(0, 1fr)); align-items: center; padding: 0 12px; white-space: nowrap; }
.ki-demo-gh { height: 30px; border: 1px solid #30363d; border-radius: 6px 6px 0 0; background: #161b22; color: #8b949e; font-size: 11.5px; font-weight: 600; }
.ki-demo-gh span:not(:first-child), .ki-demo-cell { justify-self: center; }
.ki-demo-row { height: 46px; border: 1px solid #30363d; border-top: 0; white-space: nowrap; }
.ki-demo-row:nth-last-child(2) { border-radius: 0 0 6px 6px; }
.ki-demo-cell { position: relative; width: 16px; height: 16px; }
.ki-demo-cell i { position: absolute; inset: 0; display: flex; opacity: 0; }
.ki-demo-spin { transform-box: view-box; transform-origin: 8px 8px; animation: ki-demo-spin 1s linear infinite; }
.ki-demo-echo { margin-top: 14px; color: #7ee787; font-family: var(--font-code); font-size: 12px; opacity: 0; animation: ki-demo-echo 18s ease infinite; }
"""
PLAYS = 10
KI_LINES = {"l1": 9, "l2": 10.5, "recap": 36, "n0": 37, "n1": 38, "n2": 39}
for key in KI_LINES:
    ki += f".ki-demo-{key} {{ opacity: 0; animation: ki-demo-{key} 18s linear infinite; }}\n"
for i in range(PLAYS):
    ki += f".ki-demo-p{i} {{ opacity: 0; animation: ki-demo-p{i} 18s linear infinite; }}\n"


def ki_cell_time(row, col):
    """When cell (row, col) of the matrix turns green, in percent of the loop."""
    return round(50 + col * 10 + row * 1.6, 2)


KI_ROWS, KI_COLS, KI_RUN = 5, 4, 3.5
for r in range(KI_ROWS):
    for col in range(KI_COLS):
        for st in "prd":
            ki += f".ki-demo-c{r}{col}{st} {{ animation: ki-demo-c{r}{col}{st} 18s linear infinite; }}\n"

ki_k = [
    vis("ki-demo-term", [(1, 45)]),
    vis("ki-demo-matrix", [(47, 97)]),
    vis("ki-demo-t1", [(0, 46), (98, 100)], 0.3),
    vis("ki-demo-t2", [(46, 98)], 0.3),
    vis("ki-demo-echo", [(90, 100)]),
    props("ki-demo-type1", [("0%, 2%", "width: 0; animation-timing-function: steps(36, end);"), ("7%, 100%", "width: 36ch;")]),
    props("ki-demo-type2", [("0%, 11%", "width: 0; animation-timing-function: steps(9, end);"), ("13%, 100%", "width: 9ch;")]),
    props("ki-demo-spin", [("100%", "transform: rotate(360deg);")]),
]
for key, t in KI_LINES.items():
    ki_k.append(vis(f"ki-demo-{key}", [(t, 100)], 0.3))
for i in range(PLAYS):
    ki_k.append(vis(f"ki-demo-p{i}", [(15 + i * 2, 100)], 0.3))
for r in range(KI_ROWS):
    for col in range(KI_COLS):
        t = ki_cell_time(r, col)
        ki_k.append(vis(f"ki-demo-c{r}{col}p", [(0, round(t - KI_RUN, 2))], 0.3))
        ki_k.append(vis(f"ki-demo-c{r}{col}r", [(round(t - KI_RUN, 2), t)], 0.3))
        ki_k.append(vis(f"ki-demo-c{r}{col}d", [(t, 100)], 0.3))


def build():
    """Return the generated CSS block, without the markers."""
    return (
        cl + "\n" + "\n".join(cl_k) + "\n\n"
        + al + "\n" + "\n".join(al_k) + "\n\n"
        + ki + "\n" + "\n".join(ki_k) + "\n\n"
    )


def splice(css, block):
    """Replace the text between the markers in css with block."""
    start = css.index(BEGIN) + len(BEGIN)
    end = css.index(END)
    return css[:start] + block + css[end:]


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if custom.css is out of date")
    args = parser.parse_args()

    with open(CSS_PATH, encoding="utf-8") as f:
        css = f.read()
    updated = splice(css, build())
    if args.check:
        if updated != css:
            print("assets/css/custom.css is out of date; run .github/scripts/gen_demo_css.py", file=sys.stderr)
            return 1
        print("assets/css/custom.css is up to date")
        return 0
    if updated != css:
        with open(CSS_PATH, "w", encoding="utf-8") as f:
            f.write(updated)
        print("updated assets/css/custom.css")
    else:
        print("assets/css/custom.css already up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
