repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-added-large-files
      - id: check-yaml
      - id: debug-statements
  - repo: https://github.com/commit-check/commit-check
    rev: v0.8.1
    hooks:
      - id: check-message
      - id: check-branch
      - id: check-author-name
      - id: check-author-email
