name: Auto Translate Missing Blog Posts

on:
  push:
    paths:
      - 'content/posts/**'
      - 'content/misc/**'
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  check-and-translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install google-generativeai PyYAML PyGithub

      - name: Run translation check
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/auto_translate_action.py
