# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: master
  pull_request:
    branches: master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          source:
            - 'source/_posts/**'
            - 'source/about/**'
            - 'source/daily/**'

    - name: Setup Node 13
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Build then Test
      run: |
        npm install
        npm install -g hexo-cli
        hexo generate
        hexo server > /dev/null 2>&1 &
        sleep 20 && curl -Is http://localhost:4000/ | head -n 1

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        # Set the sonar.projectBaseDir analysis property
        projectBaseDir: .

    - name: Publish
      # run only if 'source' files was changed
      if: steps.filter.outputs.source == 'true'
      run: make publish
