# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: master
  pull_request:
    branches: master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Clone code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Node 13
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Build then Test
      run: |
        npm install
        npm install -g hexo-cli
        hexo generate
        hexo server > /dev/null 2>&1 &
        sleep 20 && curl -Is http://localhost:4000/ | head -n 1

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        # Set the sonar.projectBaseDir analysis property
        projectBaseDir: .

    - name: Publish
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          source:
            - 'source/_posts/**'
      # run only if some file in 'source' folder was changed
    - if: steps.changes.outputs.source == 'true'
      run: make publish
